### ISSUE TITLE
兄弟，这个图比较完整，你把日期也加上啊

### ISSUE THREAD

**Issue by wanliyunyan** [WeNeedHome/SummaryOfLoanSuspension#19]
![b8369fd2c99fd85bac9c22438e3cba0](https://user-images.githubusercontent.com/10751248/178648242-dfb8a27d-8437-404b-97ba-a89a7a259e59.jpg)

**Comment by WeNeedHome** [comment]
我这个是根据发起人收到停贷通知后，才加入的，你可以把停贷通知发给发起人，readme 里有发起人账号
