### ISSUE TITLE
烂尾的可以不还，还不起的可以不还吗

### ISSUE THREAD

**Issue by a186r** [WeNeedHome/SummaryOfLoanSuspension#35]
烂尾的可以不还，还不起的可以不还吗，如果大家都不还，那我们算提前进入社会主义吗

**Comment by liao00** [comment]
不还可以，让银行法拍烂尾楼。。。

**Comment by omitchen** [comment]
说白了这是法律机制的缺失，开发商可以烂尾，但是银行不会停止收贷，这个机制本来就有问题，没有找到法律提供合理的解决方式。结果锅全是开发商背，损失全是人民在承担，gj 在背后默默数钱

**Comment by Athsx** [comment]
直接断供吧, 没事的, 我朋友就是, 自己用800块的租金租给老婆,租期20年, 然后直接断供, 3年过去了, 他们还是住在那套房子里面, 银行现在法也卖不动. 也没人理

**Comment by a186r** [comment]
法拍可以，你拍你的，我住我的，只要足够多的人还不起，选择不还，谁也没办法，就算全收过来法拍，拍也要拍个三五十年吧
