### ISSUE TITLE
生活在当今的中国感觉特别幸福、安全、自豪

### ISSUE THREAD

**Issue by devq111** [WeNeedHome/SummaryOfLoanSuspension#60]
你们呢

**Comment by a186r** [comment]
只要你晚上不出去吃夜宵，不把钱存银行，一不会被人打，二不会被人打，还有什么不安全的呢？

**Comment by xbsheng** [comment]
> 只要你晚上不出去吃夜宵，不把钱存银行，一不会被人打，二不会被人打，还有什么不安全的呢？
走在大街上被暴击

**Comment by NjY2NjY2** [comment]
铁铁，你改了ID，但是原来的ID的截图传出去了。原来的ID微博搜得到，我建议你微博ID也改一下…
